spring.application.name=demo
server.port=8089
spring.datasource.url=JDBC:mysql://localhost:3306/testdb
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Sanjaya@5259
spring.jpa.hibernate.ddl-auto=update
spring.ai.google.genai.api-key=AQ.Ab8RN6Kz4tDb8Vra7lz6sxDUk4XdRv3iCj9Sxb2KfyzFkpjdrw
spring.ai.google.genai.chat.model=gemini-2.5-flash