spring.application.name=demo
server.port=8089
spring.datasource.url=${DB_URL}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.jpa.hibernate.ddl-auto=update
spring.ai.google.genai.api-key=${AI_API}
spring.ai.google.genai.chat.model=${AI_MODEL}
