spring.application.name=demo
server.port=8089
spring.datasource.url=jdbc:mysql://localhost:3306/testdb
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Sanjaya@5259
spring.jpa.hibernate.ddl-auto=update
spring.ai.google.genai.api-key=AIzaSyC6hEzXabIieI-qCzNFZxpcX4s6J29QwtY
spring.ai.google.genai.chat.model=gemini-2.5-flash